let dtmYears=[],dtmTimer=null,selectedState=null,mapPaths=null,globalRateValues=[],todayIndex=-1;
const slider=document.getElementById("dtm-slider"),play=document.getElementById("dtm-play"),svg=d3.select("#dtm-map"),card=document.getElementById("dtm-state-card");
const names={1:"Alabama",2:"Alaska",4:"Arizona",5:"Arkansas",6:"California",8:"Colorado",9:"Connecticut",10:"Delaware",11:"District of Columbia",12:"Florida",13:"Georgia",15:"Hawaii",16:"Idaho",17:"Illinois",18:"Indiana",19:"Iowa",20:"Kansas",21:"Kentucky",22:"Louisiana",23:"Maine",24:"Maryland",25:"Massachusetts",26:"Michigan",27:"Minnesota",28:"Mississippi",29:"Missouri",30:"Montana",31:"Nebraska",32:"Nevada",33:"New Hampshire",34:"New Jersey",35:"New Mexico",36:"New York",37:"North Carolina",38:"North Dakota",39:"Ohio",40:"Oklahoma",41:"Oregon",42:"Pennsylvania",44:"Rhode Island",45:"South Carolina",46:"South Dakota",47:"Tennessee",48:"Texas",49:"Utah",50:"Vermont",51:"Virginia",53:"Washington",54:"West Virginia",55:"Wisconsin",56:"Wyoming"};
function unpack(data){return data.years.map(y=>{const states={};data.fips.forEach((f,i)=>states[String(f).padStart(2,"0")]={name:names[f],deaths:y[3][i],age_adjusted_rate:y[4][i]});return{year:y[0],national:{deaths:y[1],age_adjusted_rate:y[2]},states}})}
function color(v,values=globalRateValues){const s=values.filter(Number.isFinite).sort((a,b)=>a-b),lo=d3.quantileSorted(s,.02),hi=d3.quantileSorted(s,.98),t=Math.max(0,Math.min(1,(v-lo)/(hi-lo)));return d3.interpolateRgbBasis(["#20211d","#3f3c31","#716044","#a17b4e","#d2a25e","#f0c878"])(t)}
function stateRow(row,id){return row.states[String(+id).padStart(2,"0")]}
function daysInMonth(d){return new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}
function buildToday(current,seasonality){const now=new Date(),annual=Number(current?.national?.annual_baseline?.deaths),months=seasonality?.monthly_deaths,seasonTotal=Number(seasonality?.annual_deaths)||months?.reduce((a,b)=>a+Number(b||0),0),monthDeaths=Array.isArray(months)?Number(months[now.getMonth()]):NaN;if(!Number.isFinite(annual)||!Number.isFinite(seasonTotal)||!Number.isFinite(monthDeaths))throw new Error("TODAY model inputs unavailable");const national=Math.round(annual*(monthDeaths/seasonTotal)/daysInMonth(now)),sourceTotal=Number(current?.states?.source?.national_deaths)||3072666,rows=current?.states?.estimates||{},states={};Object.entries(rows).forEach(([name,r])=>{const id=Object.keys(names).find(k=>names[k]===name);if(id)states[String(+id).padStart(2,"0")]={name,deaths:national*(Number(r.final_2024_deaths)/sourceTotal),age_adjusted_rate:Number(r.age_adjusted_rate_2024)}});let bases=Object.entries(states).map(([id,r])=>({id,base:Math.floor(r.deaths),frac:r.deaths-Math.floor(r.deaths)})),remain=national-bases.reduce((a,b)=>a+b.base,0);bases.sort((a,b)=>b.frac-a.frac||a.id.localeCompare(b.id));bases.forEach((x,i)=>states[x.id].deaths=x.base+(i<remain?1:0));return{year:"TODAY",modeled:true,national:{deaths:national,age_adjusted_rate:Number(current?.states?.rate_metric?.us_rate)||722.1},states}}
function showState(id,row){selectedState=+id;const st=stateRow(row,id);if(!st)return;const hasNational=Number.isFinite(row.national.age_adjusted_rate),delta=hasNational?(st.age_adjusted_rate/row.national.age_adjusted_rate-1)*100:null;card.innerHTML='<p class="eyebrow">STATE · '+row.year+'</p><strong class="state-name">'+st.name+'</strong><div class="state-stat"><b>'+(row.modeled?'≈ ':'')+st.deaths.toLocaleString("en-US")+'</b><span>'+(row.modeled?'estimated deaths today':'resident deaths')+'</span></div><div class="state-stat rate-stat"><b class="rate-value">'+st.age_adjusted_rate.toFixed(1)+'</b><span>per 100,000 · age-adjusted</span></div><p class="state-comparison">'+(hasNational?Math.abs(delta).toFixed(1)+'% '+(delta>=0?'above':'below')+' U.S. rate':'U.S. rate verification pending')+'</p><p class="state-provenance">'+(row.modeled?'● FINAL 2024 RATE · ≈ MODELLED DAILY':'● FINAL HISTORICAL')+'</p>'}
function render(i){const row=dtmYears[i];if(!row)return;document.getElementById("dtm-year").textContent=row.year;document.querySelector(".dtm-status").textContent=row.modeled?'≈ MODELLED':'● FINAL';document.getElementById("dtm-deaths").textContent=(row.modeled?'≈ ':'')+row.national.deaths.toLocaleString("en-US");document.getElementById("dtm-rate").textContent=row.modeled?'—':Number.isFinite(row.national.age_adjusted_rate)?row.national.age_adjusted_rate.toFixed(1):"—";const era=row.modeled?'Model 0.2':row.year<=1978?'ICD-8 era':row.year<=1998?'ICD-9 era':'ICD-10 era';document.getElementById("dtm-note").textContent=row.modeled?'Model 0.2 · 2025 provisional annual baseline · 2024 final seasonality and state shares · not a live death registry':era+' · final all-cause mortality'+(row.year===1972?' · 1972 CMF uses a 50% sample weighted by 2':'');if(mapPaths){mapPaths.style("fill",d=>{const s=stateRow(row,d.id);return s?color(s.age_adjusted_rate):"#20211d"})}if(selectedState)showState(selectedState,row)}
function stopDTM(){if(dtmTimer){clearInterval(dtmTimer);dtmTimer=null}play.textContent="▶ PLAY"}
function rhythmIsGonnaGetYou(){stopDTM();play.textContent="Ⅱ PAUSE";dtmTimer=setInterval(()=>{let n=Number(slider.value)+1;if(n>Number(slider.max)){stopDTM();return}slider.value=n;render(n)},650)}
const historyFiles=[
["data/history_1968_1977.json","json"],["data/history_1978_1988.json","json"],["data/history_1989_1998.json","json"],
["data/history_1999.b64","b64"],["data/history_2000_2005.b64","b64"],["data/history_2006_2010.b64","b64"],["data/history_2011_2015.b64","b64"],["data/history_2016_2020.b64","b64"],
["data/history_2021_2024.json","json"]
];
function loadHistory([file,type]){return fetch(file,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(file+" unavailable");return type==="b64"?r.text().then(t=>JSON.parse(atob(t.trim()))):r.json()})}
Promise.all([Promise.all(historyFiles.map(loadHistory)),fetch("https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json").then(r=>r.json()),fetch("data/current.json",{cache:"no-store"}).then(r=>r.json()),fetch("data/seasonality_2024.json",{cache:"no-store"}).then(r=>r.json())]).then(([chunks,us,current,seasonality])=>{dtmYears=chunks.flatMap(unpack).sort((a,b)=>a.year-b.year);const expected=Array.from({length:57},(_,i)=>1968+i),actual=dtmYears.map(d=>d.year);if(actual.length!==57||expected.some((y,i)=>actual[i]!==y))throw new Error("DTM history continuity check failed");globalRateValues=dtmYears.flatMap(row=>Object.values(row.states).map(s=>s.age_adjusted_rate)).filter(Number.isFinite);dtmYears.push(buildToday(current,seasonality));todayIndex=dtmYears.length-1;slider.max=todayIndex;document.getElementById("tick-first").textContent=dtmYears[0].year;document.getElementById("tick-last").textContent='TODAY ≈ MODELLED';const allStates=topojson.feature(us,us.objects.states),allowed=new Set(Object.keys(dtmYears[0].states).map(Number)),states={type:"FeatureCollection",features:allStates.features.filter(d=>allowed.has(+d.id))},projection=d3.geoAlbersUsa().fitExtent([[35,35],[925,555]],states);projection.scale(projection.scale()*1.35);const p=projection.translate();projection.translate([p[0]-72,p[1]]);const path=d3.geoPath(projection),g=svg.append("g");mapPaths=g.selectAll("path").data(states.features).join("path").attr("class","state").attr("d",path).attr("tabindex",0).attr("aria-label",d=>names[+d.id]).on("mouseenter focus click",(e,d)=>showState(d.id,dtmYears[Number(slider.value)]));const reset=document.getElementById("dtm-map-reset"),zoom=d3.zoom().scaleExtent([1,8]).filter(e=>e.type!=="wheel"&&e.type!=="dblclick"&&(!(e.type==="touchstart"||e.type==="touchmove")||(e.touches&&e.touches.length>=2))).on("zoom",e=>{g.attr("transform",e.transform);reset?.classList.toggle("visible",e.transform.k!==1||e.transform.x!==0||e.transform.y!==0)});svg.call(zoom).on("dblclick.zoom",null);reset?.addEventListener("click",()=>svg.transition().duration(220).call(zoom.transform,d3.zoomIdentity));render(0)}).catch(e=>{console.error(e);document.getElementById("dtm-note").textContent="Historical map data unavailable."});
slider.addEventListener("input",()=>{stopDTM();render(Number(slider.value))});play.addEventListener("click",()=>dtmTimer?stopDTM():rhythmIsGonnaGetYou());