let dtmYears=[],dtmTimer=null,selectedState=null,mapPaths=null;
const slider=document.getElementById("dtm-slider"),play=document.getElementById("dtm-play"),svg=d3.select("#dtm-map"),card=document.getElementById("dtm-state-card");
const names={1:"Alabama",2:"Alaska",4:"Arizona",5:"Arkansas",6:"California",8:"Colorado",9:"Connecticut",10:"Delaware",11:"District of Columbia",12:"Florida",13:"Georgia",15:"Hawaii",16:"Idaho",17:"Illinois",18:"Indiana",19:"Iowa",20:"Kansas",21:"Kentucky",22:"Louisiana",23:"Maine",24:"Maryland",25:"Massachusetts",26:"Michigan",27:"Minnesota",28:"Mississippi",29:"Missouri",30:"Montana",31:"Nebraska",32:"Nevada",33:"New Hampshire",34:"New Jersey",35:"New Mexico",36:"New York",37:"North Carolina",38:"North Dakota",39:"Ohio",40:"Oklahoma",41:"Oregon",42:"Pennsylvania",44:"Rhode Island",45:"South Carolina",46:"South Dakota",47:"Tennessee",48:"Texas",49:"Utah",50:"Vermont",51:"Virginia",53:"Washington",54:"West Virginia",55:"Wisconsin",56:"Wyoming"};
function unpack(data){return data.years.map(y=>{const states={};data.fips.forEach((f,i)=>states[String(f).padStart(2,"0")]={name:names[f],deaths:y[3][i],age_adjusted_rate:y[4][i]});return{year:y[0],national:{deaths:y[1],age_adjusted_rate:y[2]},states}})}
function color(v,values){const s=values.filter(Number.isFinite).sort((a,b)=>a-b),lo=d3.quantileSorted(s,.02),hi=d3.quantileSorted(s,.98),t=Math.max(0,Math.min(1,(v-lo)/(hi-lo)));return d3.interpolateRgbBasis(["#20211d","#3f3c31","#716044","#a17b4e","#d2a25e","#f0c878"])(t)}
function stateRow(row,id){return row.states[String(+id).padStart(2,"0")]}
function showState(id,row){selectedState=+id;const s=stateRow(row,id);if(!s)return;const hasNational=Number.isFinite(row.national.age_adjusted_rate),delta=hasNational?(s.age_adjusted_rate/row.national.age_adjusted_rate-1)*100:null;card.innerHTML='<p class="eyebrow">STATE · '+row.year+'</p><strong class="state-name">'+s.name+'</strong><div class="state-stat"><b>'+s.deaths.toLocaleString("en-US")+'</b><span>resident deaths</span></div><div class="state-stat rate-stat"><b class="rate-value">'+s.age_adjusted_rate.toFixed(1)+'</b><span>per 100,000 · age-adjusted</span></div><p class="state-comparison">'+Math.abs(delta).toFixed(1)+(hasNational?Math.abs(delta).toFixed(1)+'% '+(delta>=0?'above':'below')+' U.S. rate':'U.S. rate verification pending')+'</p><p class="state-provenance">● FINAL HISTORICAL</p>'}
function render(i){const row=dtmYears[i];if(!row)return;document.getElementById("dtm-year").textContent=row.year;document.getElementById("dtm-deaths").textContent=row.national.deaths.toLocaleString("en-US");document.getElementById("dtm-rate").textContent=Number.isFinite(row.national.age_adjusted_rate)?row.national.age_adjusted_rate.toFixed(1):"—";const era=row.year<=1978?"ICD-8 era":row.year<=1998?"ICD-9 era":"ICD-10 era";document.getElementById("dtm-note").textContent=era+" · final all-cause mortality"+(row.year===1972?" · 1972 CMF uses a 50% sample weighted by 2":"");if(mapPaths){const vals=Object.values(row.states).map(s=>s.age_adjusted_rate);mapPaths.style("fill",d=>{const s=stateRow(row,d.id);return s?color(s.age_adjusted_rate,vals):"#20211d"})}if(selectedState)showState(selectedState,row)}
function stopDTM(){if(dtmTimer){clearInterval(dtmTimer);dtmTimer=null}play.textContent="▶ PLAY"}
function rhythmIsGonnaGetYou(){stopDTM();play.textContent="Ⅱ PAUSE";dtmTimer=setInterval(()=>{let n=Number(slider.value)+1;if(n>Number(slider.max)){stopDTM();return}slider.value=n;render(n)},650)}
const historyFiles=["data/history_1968_1977.json","data/history_1978_1988.json","data/history_1989_1998.json","data/history_2021_2024.json"];
Promise.all([Promise.all(historyFiles.map(file=>fetch(file,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(file+" unavailable");return r.json()}))),fetch("https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json").then(r=>r.json())]).then(([chunks,us])=>{dtmYears=chunks.flatMap(unpack).sort((a,b)=>a.year-b.year);slider.max=dtmYears.length-1;document.getElementById("tick-first").textContent=dtmYears[0].year;document.getElementById("tick-last").textContent=dtmYears.at(-1).year;const allStates=topojson.feature(us,us.objects.states),allowed=new Set(Object.keys(dtmYears[0].states).map(Number)),states={type:"FeatureCollection",features:allStates.features.filter(d=>allowed.has(+d.id))},projection=d3.geoAlbersUsa().fitExtent([[35,35],[925,555]],states);projection.scale(projection.scale()*1.35);const p=projection.translate();projection.translate([p[0]-72,p[1]]);const path=d3.geoPath(projection),g=svg.append("g");mapPaths=g.selectAll("path").data(states.features).join("path").attr("class","state").attr("d",path).attr("tabindex",0).attr("aria-label",d=>names[+d.id]).on("mouseenter focus click",(e,d)=>showState(d.id,dtmYears[Number(slider.value)]));const reset=document.getElementById("dtm-map-reset"),zoom=d3.zoom().scaleExtent([1,8]).filter(e=>e.type!=="wheel"&&e.type!=="dblclick"&&(!(e.type==="touchstart"||e.type==="touchmove")||(e.touches&&e.touches.length>=2))).on("zoom",e=>{g.attr("transform",e.transform);reset?.classList.toggle("visible",e.transform.k!==1||e.transform.x!==0||e.transform.y!==0)});svg.call(zoom).on("dblclick.zoom",null);reset?.addEventListener("click",()=>svg.transition().duration(220).call(zoom.transform,d3.zoomIdentity));render(0)}).catch(e=>{console.error(e);document.getElementById("dtm-note").textContent="Historical map data unavailable."});
slider.addEventListener("input",()=>{stopDTM();render(Number(slider.value))});play.addEventListener("click",()=>dtmTimer?stopDTM():rhythmIsGonnaGetYou());